names_list = [
            'Alice',
            'Sophia',
            'Helena',
            'Valentina',
            'Laura',
            'Isabella',
            'Manuela',
            'Júlia',
            'Heloísa',
            'Luiza',
            'Maria Luiza',
            'Lorena',
            'Lívia',
            'Giovanna',
            'Maria Eduarda',
            'Beatriz',
            'Maria Clara',
            'Cecília',
            'Eloá',
            'Lara',
            'Maria Júlia',
            'Isadora',
            'Mariana',
            'Emanuelly',
            'Ana Júlia',
            'Ana Luiza',
            'Ana Clara',
            'Melissa',
            'Yasmin',
            'Maria Alice',
            'Isabelly',
            'Lavínia',
            'Esther',
            'Sarah',
            'Elisa',
            'Antonella',
            'Rafaela',
            'Maria Cecília',
            'Liz',
            'Marina',
            'Nicole',
            'Maitê',
            'Isis',
            'Alícia',
            'Luna',
            'Rebeca',
            'Agatha',
            'Letícia',
            'Maria-',
            'Gabriela',
            'Ana Laura',
            'Catarina',
            'Clara',
            'Ana Beatriz',
            'Vitória',
            'Olívia',
            'Maria Fernanda',
            'Emilly',
            'Maria Valentina',
            'Milena',
            'Maria Helena',
            'Bianca',
            'Larissa',
            'Mirella',
            'Maria Flor',
            'Allana',
            'Ana Sophia',
            'Clarice',
            'Pietra',
            'Maria Vitória',
            'Maya',
            'Laís',
            'Ayla',
            'Ana Lívia',
            'Eduarda',
            'Mariah',
            'Stella',
            'Ana',
            'Gabrielly',
            'Sophie',
            'Carolina',
            'Maria Laura',
            'Maria Heloísa',
            'Maria Sophia',
            'Fernanda',
            'Malu',
            'Analu',
            'Amanda',
            'Aurora',
            'Maria Isis',
            'Louise',
            'Heloise',
            'Ana Vitória',
            'Ana Cecília',
            'Ana Liz',
            'Joana',
            'Luana',
            'Antônia',
            'Isabel',
            'Bruna'
        ]

if __name__ == '__main__':
    from collections import Counter
    print([k for k,v in Counter(names_list).items() if v>1])