surnames_list = [
        'Alves',
        'Monteiro',
        'Novaes',
        'Mendes',
        'Barros',
        'Freitas',
        'Barbosa',
        'Pinto',
        'Moura',
        'Cavalcanti',
        'Dias',
        'Castro',
        'Campos',
        'Cardoso',
        'Silva',
        'Souza',
        'Costa',
        'Santos',
        'Oliveira',
        'Pereira',
        'Almeida',
        'Nascimento',
        'Lima',
        'Araújo',
        'Fernandes',
        'Gomes',
        'Martins',
        'Rocha',
        'Rezende',
        'Sales',
        'Peixoto',
        'Fogaça',
        'Porto',
        'Ribeiro',
        'Duarte',
        'Moraes',
        'Ramos',
        'Ferreira',
        'Silveira',
        'Moreira',
        'Teixeira',
        'Caldeira',
        'Vieira',
        'Nogueira',
        'da Costa',
        'da Rocha',
        'da Cruz',
        'da Cunha',
        'da Mata',
        'da Rosa',
        'da Mota',
        'da Paz',
        'da Luz',
        'da Conceição',
        'das Neves',
        'Gonçalves',
        'Rodrigues',
        'Lopes',
        'Nunes',
        'Carvalho',
        'Melo',
        'Pires',
        'Jesus',
        'Aragão',
        'Viana',
        'Farias',
        'Santana',
        'Queiros',
        'Dantas',
        'Arcoverde',
        'Vasquez',
        'Rossi',
        'Russo',
        'Ferrari',
        'Esposito',
        'Bianchi',
        'Romano',
        'Colombo',
        'Ricci',
        'Marino',
        'Greco',
        'Bruno',
        'Gallo',
        'Conti',
        'Luca',
        'Mancini',
        'Giordano',
        'Rizzo',
        'Lombardi',
        'Moretti',
        'Davies', 
        'Evans', 
        'Thomas', 
        'Johnson', 
        'Wilson', 
        'Roberts', 
        'Robinson', 
        'Wright', 
        'Thompson', 
        'White', 
        'Hall', 
        'Walker', 
        'Green', 
        'Edwards', 
        'Wood', 
        'Hughes', 
        'Jackson', 
        'Turner', 
        'Lewis',
        'Harris',
    ]

if __name__ == '__main__':
    from collections import Counter
    print([k for k,v in Counter(surnames_list).items() if v>1])